services:
  komodo-telegram-alerter:
    container_name: komodo-telegram-alerter
    image: ghcr.io/andrew-codechimp/komodo-telegram-alerter:latest
    environment:
      - TZ='Europe/London'    
    ports:
      - '9121:3000'
    volumes:
      - /containers/komodo-telegram-alerter/config:/app/config:ro
    restart: unless-stopped
